name: Common Python Setup

description: Checkout, setup python, install uv
runs:
  using: "composite"    
  steps:
    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with: 
        version: "0.9.9"

    - name: Setup uv venv
      run: uv venv
      shell: bash
